In [4]:
import cv2 as cv
import numpy as np
import os
import scipy.io

In [5]:
def loadhouse():
    src = '/media/mrj/documents/AI/3D-Vision/src/modelHouse/'
    img = []
    calib = []
    for filename in os.listdir(src):
        if 'pgm' in filename:
            img_path = os.path.join(src, filename)
            img.append(cv.imread(img_path))

    src = '/media/mrj/documents/AI/3D-Vision/src/modelHouse/calib/'
    for filename in os.listdir(src):
        txt_path = os.path.join(src, filename)
        with open(txt_path, 'r') as file:
            lines = file.readlines()

        data = []
        for line in lines[0:]: 
            data.extend(map(float, line.split()))

        matrix = np.array(data).reshape((3, 4))
        calib.append(matrix)
    return img, calib


[[-6.67132440e+02  1.51866017e+01 -3.99122170e+02 -6.41710474e+01]
 [ 2.61277801e-01 -6.64130698e+02 -2.89014678e+02 -7.62961667e-01]
 [-1.36678873e-04  3.40102814e-02 -1.00064162e+00  1.69777098e-02]]
[[-5.75709508e+02  5.36472030e+01 -4.97058613e+02 -6.96358395e+02]
 [ 3.47247879e+00 -6.47354776e+02 -2.86990297e+02 -3.37416849e+01]
 [ 1.72545177e-01  1.23163530e-02 -9.73919592e-01 -2.66780545e-03]]
[[-1.73942137e+02  2.95578735e+01 -2.04739955e+02 -4.16884673e+02]
 [ 2.22632706e+00 -2.28979704e+02 -1.03123423e+02 -2.16638622e+01]
 [ 1.12864622e-01 -4.84301229e-03 -3.36216012e-01  3.90922793e-02]]
[[-1.55767020e+02  4.20515523e+01 -2.45748918e+02 -5.88315208e+02]
 [ 2.15493322e+00 -2.49343210e+02 -1.12197491e+02 -2.38297603e+01]
 [ 1.69918509e-01 -1.53620460e-02 -3.46806651e-01  1.47696838e-01]]
[[-3.17256417e+01  1.45238044e+01 -7.57606073e+01 -2.01826428e+02]
 [ 7.75740252e-01 -7.10172105e+01 -3.22456106e+01 -8.33420454e+00]
 [ 6.28717465e-02 -8.37378178e-03 -9.07588169e-02  8.70125

In [6]:
def loadbird():
    src = '/media/mrj/documents/AI/3D-Vision/src/bird_data/images/'
    img = []
    calib = []
    for filename in os.listdir(src):
        if 'ppm' in filename:
            img_path = os.path.join(src, filename)
            img.append(cv.imread(img_path))
    src = '/media/mrj/documents/AI/3D-Vision/src/bird_data/calib'
    for filename in os.listdir(src):
        if 'txt' in filename:
            txt_path = os.path.join(src, filename)
            with open(txt_path, 'r') as file:
                lines = file.readlines()

            data = []
            for line in lines[1:]: 
                data.extend(map(float, line.split()))

            matrix = np.array(data).reshape((3, 4))
            calib.append(matrix)
    return img, calib

In [7]:
def loaddin():
    src = '/media/mrj/documents/AI/3D-Vision/src/din/'
    img = []
    for filename in os.listdir(src):
        if 'ppm' in filename:
            img_path = os.path.join(src, filename)
            img.append(cv.imread(img_path))


    mat_file = scipy.io.loadmat(f"{src}/cameraCalibration.mat")

    matrixCalibration = np.array(mat_file['P'][0])
    return img, matrixCalibration